### ISSUE TITLE
全局box-sizing: border-box导致el-time-picker组件滚动错位

### ISSUE THREAD

**Issue by zcqno1** [levy9527/nuxt-element-dashboard#15]
**el-time-picker**
![image](https://user-images.githubusercontent.com/11766057/58323763-8c24fe80-7e57-11e9-943e-76d0ca481725.png)

检查发现错位原因是组件弹层的 `.el-scrollbar__wrap` 带有 `box-sizing: border-box`（从 `global.less` 里的全局设置继承）

**解决办法**
1. 恢复 `box-sizing`
```css
.el-time-pannel .el-scrollbar__wrap {
  box-sizing: initial;
}
```
2. 调整偏移块高度（原为 80px）
```css
.el-time-spinner__list::after, .el-time-spinner__list::before {
  height: 72px;
}
```
